branch-defaults:
  master:
    environment: aws-course-env
    group_suffix: null
global:
  application_name: AWSDevOps_study
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js 18 running on 64bit Amazon Linux 2
  default_region: us-east-1
  deployment_package: AWSDevOps_study.zip
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
