applicationName: 'frontend-deploy'
deploymentGroupName: 'frontend-deploy-group'
revision:
  revisionType: AppSpecContent
  appSpecContent:
    content: |
      version: 0.0
      Resources:
        - TargetService:
            Type: AWS::ECS::Service
            Properties:
              TaskDefinition: "<TASK_DEFINITION_ARN>"
              LoadBalancerInfo:
                ContainerName: "app"
                ContainerPort: 80